# Generated by Django 5.1.2 on 2024-12-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
